### ISSUE TITLE
Interest in Java & Go language starter kits?

### ISSUE THREAD

**Issue by imattman** [CodeBytes-PDX/rest-api-challenge#8]
How much interest is there in adding other language starter kits?  I'm happy to contribute starter versions (with instructions) for Java and Go using lightweight libraries.

I can also see an argument for keeping it to the current three for easier mentorship support.

**Comment by Errolyn** [comment]
I think it would be great to have other examples! feel free to add them in the same style we already have going one language per folder. Thanks for contributing!
